List<Map<String, dynamic>> chats = [
  {
    "name": "Ali Khan",
    "message": "Kahan ho bhai?",
    "time": "9:45 PM",
    "profilePic":
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnVPzkzWsfcJnM6oa_XuO55DdB4KTwtF2-iU64kzLr7Q&s",
  },
  {
    "name": "Ahmed Raza",
    "message": "Kal milte hain",
    "time": "9:30 PM",
    "profilePic":
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGJrnxEaCB3pooHFK4AvhT8r13oBN3xrd49OymaRtE2w&s",
  },
  {
    "name": "Usman",
    "message": "Assignment complete ho gaya?",
    "time": "9:15 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?q=80&w=1176&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Hamza",
    "message": "Good night bro",
    "time": "8:55 PM",
    "profilePic":
        "https://plus.unsplash.com/premium_photo-1672239496290-5061cfee7ebb?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Hassan",
    "message": "Screenshot bhejo",
    "time": "8:40 PM",
    "profilePic":
        "https://plus.unsplash.com/premium_photo-1671656349322-41de944d259b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Bilal",
    "message": "Theek hai 👍",
    "time": "8:20 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1615109398623-88346a601842?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Saad",
    "message": "Bhai ek kaam tha",
    "time": "8:05 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1581382575275-97901c2635b7?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Adeel",
    "message": "Call karna jab free ho",
    "time": "7:50 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Danish",
    "message": "Nice work 🔥",
    "time": "7:35 PM",
    "profilePic":
        "https://plus.unsplash.com/premium_photo-1672239496290-5061cfee7ebb?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Fahad",
    "message": "Kya scene hai?",
    "time": "7:20 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Zain",
    "message": "Main ghar pohanch gaya",
    "time": "7:05 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Talha",
    "message": "Kal class hai?",
    "time": "6:50 PM",
    "profilePic":
        "https://plus.unsplash.com/premium_photo-1723770023600-8083358720aa?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Shahzaib",
    "message": "Bhai notes send kar do",
    "time": "6:35 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1480429370139-e0132c086e2a?q=80&w=688&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Waleed",
    "message": "Done bro",
    "time": "6:20 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1508341591423-4347099e1f19?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Rehan",
    "message": "Khana kha liya?",
    "time": "6:05 PM",
    "profilePic":
        "http://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Arham",
    "message": "Project kaisa chal raha hai?",
    "time": "5:50 PM",
    "profilePic":
        "https://plus.unsplash.com/premium_photo-1689977968861-9c91dbb16049?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Muneeb",
    "message": "Okay 👍",
    "time": "5:35 PM",
    "profilePic":
        "https://images.unsplash.com/photo-1590086782957-93c06ef21604?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    "name": "Abdullah",
    "message": "Kal jaldi aana",
    "time": "5:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=18",
  },
  {
    "name": "Haris",
    "message": "Bhai help chahiye",
    "time": "5:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=19",
  },
  {
    "name": "Noman",
    "message": "Kya kar rahe ho?",
    "time": "4:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=20",
  },
  {
    "name": "Imran",
    "message": "See you tomorrow",
    "time": "4:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=21",
  },
  {
    "name": "Adnan",
    "message": "Bhai location bhejo",
    "time": "4:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=22",
  },
  {
    "name": "Rizwan",
    "message": "Perfect 👌",
    "time": "4:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=23",
  },
  {
    "name": "Junaid",
    "message": "Free ho?",
    "time": "3:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=24",
  },
  {
    "name": "Kamran",
    "message": "Meeting kab hai?",
    "time": "3:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=25",
  },
  {
    "name": "Shayan",
    "message": "Hahaha 😂",
    "time": "3:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=26",
  },
  {
    "name": "Daniyal",
    "message": "Bhai reply karo",
    "time": "3:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=27",
  },
  {
    "name": "Yasir",
    "message": "Thank you bro",
    "time": "2:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=28",
  },
  {
    "name": "Sami",
    "message": "Kal ka plan kya hai?",
    "time": "2:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=29",
  },
  {
    "name": "Rafay",
    "message": "Bhai online ho?",
    "time": "2:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=30",
  },
  {
    "name": "Asad",
    "message": "Good morning",
    "time": "2:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=31",
  },
  {
    "name": "Moiz",
    "message": "File bhej di hai",
    "time": "1:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=32",
  },
  {
    "name": "Ayan",
    "message": "Check kar lena",
    "time": "1:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=33",
  },
  {
    "name": "Ahsan",
    "message": "Nice 👍",
    "time": "1:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=34",
  },
  {
    "name": "Farhan",
    "message": "Main aa raha hoon",
    "time": "1:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=35",
  },
  {
    "name": "Waqas",
    "message": "Kahan milna hai?",
    "time": "12:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=36",
  },
  {
    "name": "Sufyan",
    "message": "Okay done",
    "time": "12:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=37",
  },
  {
    "name": "Huzaifa",
    "message": "Bhai call kar",
    "time": "12:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=38",
  },
  {
    "name": "Ehtisham",
    "message": "Kya hua?",
    "time": "12:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=39",
  },
  {
    "name": "Shahzaib",
    "message": "Bas aa gaya",
    "time": "11:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=40",
  },
  {
    "name": "Murtaza",
    "message": "Bhai ek minute",
    "time": "11:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=41",
  },
  {
    "name": "Hamdan",
    "message": "Kya tum free ho?",
    "time": "11:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=42",
  },
  {
    "name": "Ibrahim",
    "message": "Kal milte hain bro",
    "time": "11:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=43",
  },
  {
    "name": "Zubair",
    "message": "All good",
    "time": "10:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=44",
  },
  {
    "name": "Shoaib",
    "message": "Bhai photo bhejo",
    "time": "10:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=45",
  },
  {
    "name": "Rameez",
    "message": "Main busy hoon",
    "time": "10:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=46",
  },
  {
    "name": "Saif",
    "message": "Baad me baat karta hoon",
    "time": "10:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=47",
  },
  {
    "name": "Ammar",
    "message": "Great idea!",
    "time": "9:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=48",
  },
  {
    "name": "Faisal",
    "message": "Bhai kya haal hai?",
    "time": "9:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=49",
  },
  {
    "name": "Owais",
    "message": "See you soon",
    "time": "9:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=50",
  },
  {
    "name": "Areeb",
    "message": "Bhai document bhej do",
    "time": "9:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=51",
  },
  {
    "name": "Sameer",
    "message": "Theek hai bhai",
    "time": "8:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=52",
  },
  {
    "name": "Mustafa",
    "message": "Kya update hai?",
    "time": "8:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=53",
  },
  {
    "name": "Aqib",
    "message": "Bhai mil sakte ho?",
    "time": "8:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=54",
  },
  {
    "name": "Shahmir",
    "message": "Done 👍",
    "time": "8:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=55",
  },
  {
    "name": "Awais",
    "message": "Good luck bro",
    "time": "7:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=56",
  },
  {
    "name": "Sarmad",
    "message": "Bhai notes chahiye",
    "time": "7:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=57",
  },
  {
    "name": "Hammad",
    "message": "Okay bro",
    "time": "7:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=58",
  },
  {
    "name": "Abbas",
    "message": "Kahan ho?",
    "time": "7:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=59",
  },
  {
    "name": "Rayan",
    "message": "Main ghar par hoon",
    "time": "6:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=60",
  },
  {
    "name": "Arsalan",
    "message": "Call me",
    "time": "6:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=61",
  },
  {
    "name": "Naveed",
    "message": "Bhai kya plan hai?",
    "time": "6:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=62",
  },
  {
    "name": "Rashid",
    "message": "Good job 👏",
    "time": "6:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=63",
  },
  {
    "name": "Irfan",
    "message": "Bhai sun",
    "time": "5:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=64",
  },
  {
    "name": "Jibran",
    "message": "Kya haal hai?",
    "time": "5:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=65",
  },
  {
    "name": "Rafay",
    "message": "Screenshot bhej",
    "time": "5:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=66",
  },
  {
    "name": "Zeeshan",
    "message": "Okay 👍",
    "time": "5:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=67",
  },
  {
    "name": "Naeem",
    "message": "Bhai busy ho?",
    "time": "4:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=68",
  },
  {
    "name": "Taimoor",
    "message": "Main nikal raha hoon",
    "time": "4:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=69",
  },
  {
    "name": "Saqlain",
    "message": "Kal ka kaam yaad hai?",
    "time": "4:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=70",
  },
  {
    "name": "Rauf",
    "message": "Bhai ek help",
    "time": "4:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=71",
  },
  {
    "name": "Furqan",
    "message": "Milte hain",
    "time": "3:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=72",
  },
  {
    "name": "Kashif",
    "message": "Theek hai",
    "time": "3:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=73",
  },
  {
    "name": "Shahryar",
    "message": "Bhai reply dena",
    "time": "3:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=74",
  },
  {
    "name": "Azan",
    "message": "Kya kar rahe ho?",
    "time": "3:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=75",
  },
  {
    "name": "Rameez",
    "message": "Good night",
    "time": "2:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=76",
  },
  {
    "name": "Wajid",
    "message": "Kal baat karte hain",
    "time": "2:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=77",
  },
  {
    "name": "Saqib",
    "message": "Bhai online aao",
    "time": "2:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=78",
  },
  {
    "name": "Nabeel",
    "message": "Okay sure",
    "time": "2:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=79",
  },
  {
    "name": "Azeem",
    "message": "Bhai kya hua?",
    "time": "1:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=80",
  },
  {
    "name": "Sohail",
    "message": "File check karo",
    "time": "1:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=81",
  },
  {
    "name": "Waqar",
    "message": "Nice bro",
    "time": "1:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=82",
  },
  {
    "name": "Haroon",
    "message": "Bhai kal milna",
    "time": "1:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=83",
  },
  {
    "name": "Younis",
    "message": "Done ho gaya",
    "time": "12:50 AM",
    "profilePic": "https://i.pravatar.cc/150?img=84",
  },
  {
    "name": "Aftab",
    "message": "Bhai call karna",
    "time": "12:35 AM",
    "profilePic": "https://i.pravatar.cc/150?img=85",
  },
  {
    "name": "Rizwan",
    "message": "Kahan ho bhai?",
    "time": "12:20 AM",
    "profilePic": "https://i.pravatar.cc/150?img=86",
  },
  {
    "name": "Sajid",
    "message": "Good night bro",
    "time": "12:05 AM",
    "profilePic": "https://i.pravatar.cc/150?img=87",
  },
  {
    "name": "Majid",
    "message": "Kal milte hain",
    "time": "11:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=88",
  },
  {
    "name": "Akbar",
    "message": "Bhai help chahiye",
    "time": "11:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=89",
  },
  {
    "name": "Asif",
    "message": "Okay bro 👍",
    "time": "11:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=90",
  },
  {
    "name": "Shafiq",
    "message": "Kya scene hai?",
    "time": "11:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=91",
  },
  {
    "name": "Ejaz",
    "message": "Bhai free ho?",
    "time": "10:50 PM",
    "profilePic": "https://i.pravatar.cc/150?img=92",
  },
  {
    "name": "Salman",
    "message": "Main aa raha hoon",
    "time": "10:35 PM",
    "profilePic": "https://i.pravatar.cc/150?img=93",
  },
  {
    "name": "Faisal",
    "message": "Check kar lena",
    "time": "10:20 PM",
    "profilePic": "https://i.pravatar.cc/150?img=94",
  },
  {
    "name": "Nadir",
    "message": "Bhai sun raha hai?",
    "time": "10:05 PM",
    "profilePic": "https://i.pravatar.cc/150?img=95",
  },
  {
    "name": "Sami",
    "message": "Good work 🔥",
    "time": "9:55 PM",
    "profilePic": "https://i.pravatar.cc/150?img=96",
  },
  {
    "name": "Rayan",
    "message": "Kal ka kya plan?",
    "time": "9:45 PM",
    "profilePic": "https://i.pravatar.cc/150?img=97",
  },
  {
    "name": "Adeel",
    "message": "Bhai milte hain",
    "time": "9:30 PM",
    "profilePic": "https://i.pravatar.cc/150?img=98",
  },
  {
    "name": "Haris",
    "message": "Theek hai 👍",
    "time": "9:15 PM",
    "profilePic": "https://i.pravatar.cc/150?img=99",
  },
  {
    "name": "Ahmed",
    "message": "Allah Hafiz",
    "time": "9:00 PM",
    "profilePic": "https://i.pravatar.cc/150?img=100",
  },
];
